import { describe, expect, it } from "vitest";

import { convert, type ConvertWarning } from "../src/index.js";
import { listDocxParts, readDocxPart, writeFixture } from "./helpers/docx.js";
import { normalizeOoxml } from "./helpers/normalize.js";

/**
 * End-to-end golden test.
 *
 * `tests/golden-render.test.ts` locks the *renderer* down against a model built
 * by hand. This one locks down the whole public pipeline — `convert()`, which
 * means the parser, the image pass and the renderer wired together — against
 * real markdown, of the kind an LLM actually emits.
 *
 * It writes each `.docx` to `tests/__fixtures__/out/`, where CI's LibreOffice
 * gate (`scripts/docx-validity.mjs`) opens it for real, then unzips it and
 * snapshots the normalised parts. Everything nondeterministic is scrubbed in
 * `tests/helpers/normalize.ts`, so the snapshot must be byte-stable: two
 * `pnpm test` runs in a row produce zero churn.
 */

/** A real 8x4 PNG (solid #2F5496), so the image path is exercised without I/O. */
const PNG_DATA_URI =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAECAIAAAA8r+mnAAAAEUlEQVR42mPQD5mGFTFQTwIA0B4jIb0iwL8AAAAASUVORK5CYII=";

/**
 * A ChatGPT-shaped answer: every construct downword supports, in the order and
 * density LLM output actually uses them.
 */
const SAMPLE = `# Migrating to downword

A short guide, with **bold**, *italic*, ~~struck~~ and \`inline code\`.

## Why

> downword builds a real OOXML package in your browser.
>
> > Nothing leaves the tab.

## Steps

1. Install the package:

   \`\`\`sh
   npm install downword
   \`\`\`

2. Call it:

   \`\`\`ts
   import { convert } from "downword";

   const bytes = await convert("# Hello");
   \`\`\`

3. Ship it.

### Checklist

- [x] Read the docs
- [ ] Write a test
  - [ ] ...a good one

### Comparison

| Tool       | Runs offline | Real .docx |
| ---------- | :----------: | ---------: |
| downword   | yes          |        yes |
| pandoc     | yes          |        yes |
| some SaaS  | no           |      maybe |

---

![The logo](${PNG_DATA_URI})

![Missing on purpose](./nope.png)

See the [docs](https://example.com/docs) or jump to [Why](#why).
A dangling anchor: [nowhere](#nowhere).

Footnotes work too[^why].

[^why]: Because Word supports them, and LLMs emit them.
`;

describe("golden: a full LLM-shaped document", () => {
  it("matches the committed word/document.xml snapshot", async () => {
    const warnings: ConvertWarning[] = [];
    const bytes = await convert(SAMPLE, {
      metadata: {
        title: "Migrating to downword",
        author: "downword",
        subject: "Golden fixture",
        description: "Generated by packages/core/tests/golden.test.ts",
        keywords: ["markdown", "docx"],
      },
      onWarning: (warning) => warnings.push(warning),
    });

    await writeFixture("golden-full.docx", bytes);

    expect(normalizeOoxml(await readDocxPart(bytes, "word/document.xml"))).toMatchSnapshot(
      "word/document.xml",
    );
    expect(normalizeOoxml(await readDocxPart(bytes, "word/numbering.xml"))).toMatchSnapshot(
      "word/numbering.xml",
    );
    expect(normalizeOoxml(await readDocxPart(bytes, "word/footnotes.xml"))).toMatchSnapshot(
      "word/footnotes.xml",
    );
    expect(normalizeOoxml(await readDocxPart(bytes, "docProps/core.xml"))).toMatchSnapshot(
      "docProps/core.xml",
    );
    // Nothing in the sample can be fetched, so every warning here is a
    // deliberate one; a new warning showing up is a diff worth reviewing.
    expect(warnings).toMatchSnapshot("warnings");
  });

  it("matches the committed package layout snapshot", async () => {
    expect(await listDocxParts(await convert(SAMPLE))).toMatchSnapshot("zip entries");
  });

  it("matches the committed snapshot for an empty document", async () => {
    const bytes = await convert("");

    await writeFixture("golden-empty.docx", bytes);

    expect(normalizeOoxml(await readDocxPart(bytes, "word/document.xml"))).toMatchSnapshot(
      "empty word/document.xml",
    );
  });

  it("is deterministic across repeated conversions in one process", async () => {
    const first = await convert(SAMPLE);
    const second = await convert(SAMPLE);

    expect(normalizeOoxml(await readDocxPart(second.slice(), "word/document.xml"))).toBe(
      normalizeOoxml(await readDocxPart(first.slice(), "word/document.xml")),
    );
  });
});
