import { describe, expect, it } from "vitest";

import { convert } from "../src/index.js";
import { listDocxParts, readDocxPart, writeFixture } from "./helpers/docx.js";
import { normalizeOoxml } from "./helpers/normalize.js";

/**
 * Golden test.
 *
 * Generates a real `.docx`, writes it to `tests/__fixtures__/out/` (where CI's
 * LibreOffice gate picks it up - see scripts/docx-validity.mjs), then unzips it
 * and snapshots the normalised `word/document.xml`.
 *
 * The snapshot must be byte-stable: `pnpm test` twice in a row produces zero
 * churn. Everything nondeterministic is scrubbed in tests/helpers/normalize.ts.
 */

const SAMPLE = [
  "# downword golden fixture",
  "",
  "First paragraph with some prose.",
  "",
  "Second paragraph, so the document has more than one block.",
  "",
  "- not a list yet (T0 scaffold emits plain paragraphs)",
].join("\n");

describe("golden: minimal document", () => {
  it("matches the committed word/document.xml snapshot", async () => {
    const { bytes } = await convert(SAMPLE, {
      title: "downword golden fixture",
      creator: "downword",
      description: "Generated by packages/core/tests/golden.test.ts",
    });

    await writeFixture("golden-minimal.docx", bytes);

    const documentXml = await readDocxPart(bytes, "word/document.xml");
    expect(normalizeOoxml(documentXml)).toMatchSnapshot("word/document.xml");
  });

  it("matches the committed package layout snapshot", async () => {
    const { bytes } = await convert(SAMPLE);
    expect(await listDocxParts(bytes)).toMatchSnapshot("zip entries");
  });

  it("matches the committed snapshot for an empty document", async () => {
    const { bytes } = await convert("");

    await writeFixture("golden-empty.docx", bytes);

    const documentXml = await readDocxPart(bytes, "word/document.xml");
    expect(normalizeOoxml(documentXml)).toMatchSnapshot("empty word/document.xml");
  });

  it("is deterministic across repeated conversions in one process", async () => {
    const first = await convert(SAMPLE);
    const second = await convert(SAMPLE);

    const firstXml = normalizeOoxml(await readDocxPart(first.bytes, "word/document.xml"));
    const secondXml = normalizeOoxml(await readDocxPart(second.bytes, "word/document.xml"));

    expect(secondXml).toBe(firstXml);
  });
});
